name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache .buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        id: build_apk
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: |
            buildozer android clean
            buildozer -v android debug 2>&1 | tee build.log
            if ls bin/*.apk 1> /dev/null 2>&1; then
              echo "built=true" >> $GITHUB_OUTPUT
            else
              echo "built=false" >> $GITHUB_OUTPUT
            fi
          buildozer_version: stable

      - name: Upload APK artifact
        if: steps.build_apk.outputs.built == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: CuyBot-APK
          path: bin/*.apk

      - name: Upload build logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: build.log
